document.write("<li><a href='31.php'>三（1）班</a></li>")
document.write("<li><a href='32.php'>三（2）班</a></li>")
document.write("<li><a href='41.php'>四（1）班</a></li>")
document.write("<li><a href='51.php'>五（1）班</a></li>")
document.write("<li><a href='52.php'>五（2）班</a></li>")
document.write("<li><a href='61.php'>六（1）班</a></li>")
document.write("<li><a href='62.php'>六（2）班</a></li>")
