document.write("<h3>联系作者：</h3>")
document.write("<p>邮箱：<a href='mailto:183328415@qq.com'>183328415@qq.com</a></p>")
document.write("<p>电话：18983169358</p>")
document.write("<p><a href='http://25599e7l23.zicp.vip/wordpress/' target='_blank' >My博客</a></p>")
document.write("<p><a href='http://25599e7l23.zicp.vip/nextcloud/' target='_blank' >NextCloud</a></p>")
document.write("<p><a href='http://daz.unaux.com/' target='_blank' >免费空间：daz.unaux.com</a></p>")
document.write("<div class='fakeimg' style='height:20px;'><a href='http://360fbb1a.nat123.fun/' target='_blank' >备用域名nat123</a></div>")
