document.write("<a href='http://www.miitbeian.gov.cn/publish/query/indexFirst.action'>渝ICP备?号-1</a>")
document.write("<img src='./images/beian.png' style='float:center;'/>")
document.write("<a href='http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=50011702500181'>渝公网安备?号</a>")
document.write("<hr>")
document.write("Copy Right 2023 By daz.cq.cn")
