document.write("<h3>软件资源：</h3>")
document.write("<ul>")
document.write("<li><a href='https://xinkuaiji.github.io/it/%E6%8C%87%E6%B3%95%E7%BB%83%E4%B9%A0.exe' target='_blank'>指法练习.exe</a></li>")
document.write("<li><a href='https://official-package.wpscdn.cn/wps/download/WPS_Setup_17857.exe' target='_blank'>Wps办公软件</a></li>")
document.write("<li><a href='https://www.mlxx313.com/' target='_blank'>重庆信息科技活动平台</a></li>")
document.write("<li><a href='https://oss.zmrobo.com/mlblock/mlblock_1.0.30_win.exe' target='_blank'>五、六年级：MlBlock</a></li>")
document.write("<li><a href='https://makecode.trafficmanager.cn/ghdl/2924dd3870b2530499eb3453c43da3c5/makecode-microbit-setup-win64.exe' target='_blank'>课后服务：MakeCode</a></li>")
document.write("<li><a href='https://www.zybuluo.com/mdeditor'  target='_blank'>在线画流程图</a></li>")
document.write("</ul>")
document.write("<h3>教程手册：</h3>")
document.write("<ul>")
document.write("<li><a href='http://daz.unaux.com/Course/Web_Course_Debian12.5.0/Web_Course_Debian12.5.0.pdf' target='_blank'>Web_Course_Debian12.5.0.pdf</a></li>")
document.write("<li><a href='http://daz.unaux.com/Course/Scratch3_Course/Scratch3_Course.pdf' target='_blank'>Scratch3_Course.pdf</a></li>")
document.write("</ul>")
