document.write(" <ul>")
document.write("<li><a href='https://xinkuaiji.github.io/it' target='_blank'><img border='0' src='./images/Connect_logo_3.png' /></a> </li>")
document.write("<li><a href="http://10.144.192.9/makecode-microbit-setup-win64.exe"  target="_blank">学校内网下载MakeCode</a></li>")
document.write("<li><a href="https://makecode.trafficmanager.cn/ghdl/2924dd3870b2530499eb3453c43da3c5/makecode-microbit-setup-win64.exe"  target="_blank">外网官网下载MakeCode</a></li>")
document.write("<li><a href="http://10.144.192.9/mlblock_1.0.26_win.exe"  target="_blank">学校内网下载MlBlock</a></li>")
document.write("<li><a href="https://res.cqup.com.cn/resource/resource/?category=3631"  target="_blank">重庆大学出版社官网下载MlBlock</a></li>")
document.write(" </ul>")
