document.write(" <ul>")
document.write("<li><a href='http://www.xinkuaiji.cn/blog/wp-login.php' target='_blank'><img border='0' src='./images/Connect_logo_3.png' /></a> </li>")
document.write("<li><a href='https://vpn.12371.gov.cn' target='_blank'>12371党建平台</a></li>")
document.write("<li><a href='http://www.cqsw.gov.cn/cqsswj/nsfw/xzfw/rjxz/' target='_blank'>个税软件</a></li>")
document.write("<li><a href='http://dzswj.cq-l-tax.gov.cn' target='_blank'>重庆电子税务局 </a></li>")
document.write("<li><a href='http://www.fs.cq.gov.cn:8082/' target='_blank'>财政非税票据 </a></li>")
document.write("<li><a href='http://222.179.142.151:9797/zcgl' target='_blank'>固定资产管理 </a></li>")
document.write("<li><a href='https://wenku.baidu.com/p/%E9%87%8D%E5%BA%86%E6%96%B0%E4%BC%9A%E8%AE%A1' target='_blank'>会计考试资源 </a></li>")
document.write("<li><a href='https://wenku.baidu.com/p/twitba' target='_blank'>小学考试资源 </a></li>")
document.write("<li><a href='http://zxxs.emis.cq.cn' target='_blank'>义务教育营养午餐 </a></li>")
document.write("<li><a href='http://222.180.174.52/' target='_blank'>学前资助 </a></li>")
document.write("</ul>")