document.write(" <ul>")
document.write("<li><a href='https://xinkuaiji.github.io/it' target='_blank'><img border='0' src='./images/Connect_logo_3.png' /></a> </li>")
document.write("<li><a href='https://makecode.trafficmanager.cn/ghdl/2924dd3870b2530499eb3453c43da3c5/makecode-microbit-setup-win64.exe'  target='_blank'>外网官网下载MakeCode</a></li>")
document.write("<li><a href='https://res.cqup.com.cn/resource/resource/?category=3631'  target='_blank'>重大出版社下载MlBlock</a></li>")
document.write("<li><a href='./it/指法练习.exe'  target='_blank'>指法练习.exe</a></li>")
document.write(" </ul>")
