document.write("<h3>软件资源：</h3>")
document.write("<ul>")
document.write("<li><a href='https://www.cnki.net/' target='_blank'>中国知网</a></li>")
document.write("<li><a href='https://www.mlxx313.com/' target='_blank'>重庆信息科技活动平台</a></li>")
document.write("<li><a href='http://camp.deep-code.cn/' target='_blank'>三江编程马拉松</a></li>")
document.write("<li><a href='https://www.zmrobo.com/' target='_blank'>中鸣机器人</a></li>")
document.write("<li><a href='https://www.yuque.com/zmrobo/ofz1xb' target='_blank'>启智板函数说明</a></li>")
document.write("<li><a href='https://www.ybccode.com/' target='_blank'>猿编程</a></li>")
document.write("</ul>")
document.write("<h3>教程手册：</h3>")
document.write("<ul>")
document.write("<li><a href='https://xinkuaiji.github.io/pdf/Web_Course_Debian12.5.0.pdf' target='_blank'>Web_Course_Debian12.5.0.pdf</a></li>")
document.write("<li><a href='https://xinkuaiji.github.io/pdf/PHP&MySql.pdf' target='_blank'>PHP&MySql.pdf</a></li>")
document.write("</ul>")
