document.write("<a href='./index.html'>网站首页</a>")
document.write("<a href='http://daz.unaux.com/it/it.php' target='_blank'>信息科技</a>")
document.write("<a href='./acs.html'>课后服务</a>")
document.write("<a href='./pc.html'>编程竞赛</a>")
document.write("<a href='./aow.html'>作品展示</a>")
document.write("<a href='./id.html'>教学设计</a>")
document.write("<a href='http://255v99i723.oicp.vip/' target='_blank'>任务管理</a>")
document.write("<a href='http://daz.unaux.com/vfm/' target='_blank'>简易网盘</a>")
document.write("<a href='./minecraft.html' target='_blank' style='float:right'>我的世界</a>")
