document.write(" <ul>")
document.write("<li><a href='./index.html' >网站首页 </a> </li>")
document.write("<li><a href='comacc.html'>企业会计 </a></li>")
document.write("<li><a href='eduacc.html'>财政会计 </a></li>")
document.write(" <li><a href='partybuild.html'>信息科技</a></li>")
document.write("<li><a href='./blog'>我的博客</a></li>")
document.write("<li><a href='https://github.com/xinkuaiji/xinkuaiji.github.io' target='_blank'>网站源码</a></li>")
document.write("</ul>")
