document.write(" <ul>")
document.write("<li><a href='./index.html' >网站首页 </a> </li>")
document.write("<li><a href='comacc.html'>信息科技 </a></li>")
document.write("<li><a href='eduacc.html'>课后服务 </a></li>")
document.write(" <li><a href='student.html'>学生作品</a></li>")
document.write("<li><a href='./Python.html'>Python编程</a></li>")
document.write("<li><a href='https://github.com/xinkuaiji/xinkuaiji.github.io' target='_blank'>网站源码</a></li>")
document.write("</ul>")
